### ISSUE TITLE
第二步一直不成功？ 

### ISSUE THREAD

**Issue by agonyice123** [iliul/porndl#3]
$ pip3 install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by iliul** [comment]
切换到源码目录下执行
> cd porndl
> pip3 install -r requirements.txt

**Comment by agonyice123** [comment]
好像问题是出在 - -我安装的 pip给装在python 2.7的目录下了   新安装的 python3.5版本被完美忽略了 - -。

OS X系统。

**Comment by iliul** [comment]
那你用Python3的建个虚拟环境,然后在里面跑.
